#!/bin/bash

# ensure webserver user permissions on /srv
chown www-data:www-data /srv
chown www-data:www-data /srv/var

# # Setup config
# /usr/local/bin/setup-config

# # Start Redis
# /etc/init.d/redis_6379 start

# Start the php-fpm service
/usr/local/sbin/php-fpm
