# nginx:
#   image: 'monbelle/resty:latest'
#   # build: docker-images/nginx
#   ports:
#     - 80:80
#     - 443:443
#   links:
#     - phpfpm
#     - db
#   volumes_from:
#     - appdata
#
# appdata:
#   image: tianon/true
#   volumes:
#     - ./volumes/www:/srv/www
#     - ./volumes/config/nginx/nginx.conf:/etc/nginx/nginx.conf
#     - ./volumes/config/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
#     - ./volumes/config/resty/nginx.conf:/usr/local/openresty/nginx/conf/nginx.conf
#     - ./volumes/config/phpfpm/etc/php/php.ini:/usr/local/etc/php/php.ini
#     - ./volumes/config/phpfpm/etc/php-fpm.d/www.conf:/usr/local/etc/php-fpm.d/www.conf
#     - ./volumes/config/phpfpm/etc/php/zend:/usr/local/etc/php/zend
#     - ./volumes/config/phpfpm/etc/php-fpm.conf:/usr/local/etc/php-fpm.conf
#     - ./volumes/config/composer:/var/www/.composer
#     - ./volumes/config/composer:/root/.composer
#     - ./volumes/config/composer/auth.json:/srv/www/auth.json
# #    - ./www/app/code:/srv/www/app/code
#
#
# phpfpm:
#   image: mageinferno/magento2-php:5.6.20-fpm-0
#   # build: docker-images/phpfpm
#   links:
#     - db
#   volumes_from:
#     - appdata
#   environment:
#     - ENV PHP_MEMORY_LIMIT=1G

db:
  image: mariadb:10.1.13
  ports:
    - 3333:3306
  # volumes_from:
  #   - dbdata
  environment:
    - MYSQL_ROOT_PASSWORD=magento2
    - MYSQL_DATABASE=magento2
    - MYSQL_USER=magento2
    - MYSQL_PASSWORD=magento2

# dbdata:
#   image: tianon/true
#   volumes:
#     - /var/lib/mysql

# setup:
#   image: mageinferno/magento2-php:5.6.20-fpm-0
#   command: /usr/local/bin/mage-setup
#   links:
#     - db
#   volumes_from:
#     - appdata
#   environment:
#     - M2SETUP_DB_HOST=db
#     - M2SETUP_DB_NAME=magento2
#     - M2SETUP_DB_USER=magento2
#     - M2SETUP_DB_PASSWORD=magento2
#     - M2SETUP_BASE_URL=http://docker.local/
#     - M2SETUP_ADMIN_FIRSTNAME=Admin
#     - M2SETUP_ADMIN_LASTNAME=User
#     - M2SETUP_ADMIN_EMAIL=dummy@gmail.com
#     - M2SETUP_ADMIN_USER=magento2
#     - M2SETUP_ADMIN_PASSWORD=magento2
#     - M2SETUP_VERSION=2.0.4
#     - M2SETUP_USE_SAMPLE_DATA=false
#     - M2SETUP_USE_ARCHIVE=true
