#!/bin/sh

MAGENTO_INSTALLABLE = /backups/magento2-latest.tar.gz
set -x

chmod u+x bin/*

rm -rf /srv/var/
mkdir -p /srv/var/log
mkdir -p /srv/var/php-sessions

if [ ! -f $MAGENTO_INSTALLABLE ]; then
    echo "Downloading latest magento installable to $MAGENTO_INSTALLABLE ..."
    wget -P $MAGENTO_INSTALLABLE https://magento.mirror.hypernode.com/releases/magento2-latest.tar.gz
fi

cp /root/.composer/auth.json ./

bin/magento setup:install \
  --db-host=$M2SETUP_DB_HOST \
  --db-name=$M2SETUP_DB_NAME \
  --db-user=$M2SETUP_DB_USER \
  --db-password=$M2SETUP_DB_PASSWORD \
  --base-url=$M2SETUP_BASE_URL \
  --backend-frontname=$M2SETUP_ADMIN_URL\
  --admin-firstname=$M2SETUP_ADMIN_FIRSTNAME \
  --admin-lastname=$M2SETUP_ADMIN_LASTNAME \
  --admin-email=$M2SETUP_ADMIN_EMAIL \
  --admin-user=$M2SETUP_ADMIN_USER \
  --admin-password=$M2SETUP_ADMIN_PASSWORD \
  --language=$M2SETUP_LANGUAGE \
  --currency=$M2SETUP_CURRENCY \
  --timezone=$M2SETUP_TIMEZONE \
  --use-secure=$M2SETUP_USE_SSL \
  --base-url-secure=$M2SETUP_BASE_URL_SSL \
  --use-secure-admin=$M2SETUP_USE_SSL_ADMIN \
  --session-save=files \
  $M2SETUP_OPTIONS

bin/magento sampledata:deploy

# composer require \
#     stripe/stripe-php:2.*
#     mundipagg/mundipagg-one-php \
#     ebizmarts/magento2-magemonkey \
#     # mozgbrasil/magento2-correios

# mkdir app/code
# cp -r /backups/Mundipagg/ app/code/

# bin/magento cache:disable config full_page
bin/magento setup:upgrade
bin/magento indexer:reindex
