#!/bin/sh
#
# Set the correct file permissions for Magento 2
# at startup.

chgrp -R 33 /srv/www
chmod -R g+rs /srv/www

chmod -R ug+rws /srv/www/html/pub/errors
chmod -R ug+rws /srv/www/html/pub/static
chmod -R ug+rws /srv/www/html/pub/media
chmod -R ug+rws /srv/www/html/app/etc
chmod -R ug+rws /srv/www/html/var

chmod ug+x /srv/www/html/bin/magento
